#!/bin/sh
#
# Start stp-tools
#

start() {
	echo -n "Starting bluetooth sybsystem..."
	btattach -B /dev/ttymxc1 -P bcm&
	sleep 3
	hciconfig hci0 up
        echo "OK"
}

stop() {
	printf "Stopping wireless communications: "
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart|reload}"
	exit 1
esac

exit $?
