#!/bin/sh
#
# Start mounting
#

start() {
	printf "Prepare and mounting overlay filesystems: "
	modprobe overlay # load overlayfs module
	echo "OK"
	printf "Prepare bluetooth communicatons: "
	btattach -B /dev/ttyS0 -P bcm&
	echo "OK"
	printf "Prepare WiFi communicatons: "
	modprobe brcmfmac
	echo "OK"
}

stop() {
	printf "Unmounting filesystems: "
#	umount /opt/speakingcity
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart|reload}"
	exit 1
esac

exit $?
