#!/bin/sh
##############################################################################
#   SpeakingCity   special   init   script   for   prepare   root   device   #
##############################################################################

# Mount /proc (required for other mount operations)
mount -t proc proc /proc

# Mount read-write filesystem
until mount /dev/mmcblk0p3 /overlay; do
    # Format read-write filesystem, if not mounted
    # All seetiing will be restored to defaults
    mke2fs -L SpeakingCity_Root /dev/mmcblk0p3
done

# Create required directoryes, if not exist
mkdir -p /overlay/ro
mkdir -p /overlay/rw
mkdir -p /overlay/old
mkdir -p /overlay/work
mkdir -p /overlay/root

# load wifi & bluetooth modules
modprobe brcmfmac
hciattach /dev/ttyS0 bcm43xx 460800 noflow&
hciconfig hci0 up

# Mount root fs to /overlay/ro
mount -o bind / /overlay/ro
# Mount overlayed rootfs (rw) to /overlay/root
mount -t overlay overlay /overlay/root -o lowerdir=/overlay/ro,upperdir=/overlay/rw,workdir=/overlay/work

# Move rootfs to /overlay/root
cd /overlay/root
pivot_root . mnt
# ... mount again /dev
mount -t devtmpfs devtmpfs /dev
mount -t proc proc /proc
# ... cleanup unneeded directory mounting/binding
mount -o move /mnt/overlay /overlay
umount /mnt/dev
umount /mnt/proc
# ... and exec init
exec chroot . /sbin/init </dev/console >/dev/console 2>&1
# This commands not accessible, but need for ceanup (run them on init)
umount /mnt
