#!/bin/sh
#
# Start stp-tools
#

start() {
	printf "load wifi & bluetooth modules: "
	modprobe brcmfmac
	hciattach /dev/ttyS0 bcm43xx 460800 noflow&
	sleep 3
	hciconfig hci0 up
        echo "OK"
}

stop() {
	printf "Stopping wireless communications: "
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart|reload}"
	exit 1
esac

exit $?
