#!/bin/sh
#
# Start stp-tools
#

start() {
	printf "load wifi & bluetooth modules: "
	modprobe brcmfmac
	hciattach /dev/ttyS0 bcm43xx 460800 noflow&
	sleep 3
	hciconfig hci0 up
	echo "OK"
	printf "Add ap0 interface to wlan0 devices: "
	MAC=`cat /sys/class/net/wlan0/address`
	iw phy phy0 interface add ap0 type __ap
	ip link set ap0 address ${MAC}
	echo "OK"
	printf "Prepare modem driver: "
	echo 23 > /sys/class/gpio/export
	echo 24 > /sys/class/gpio/export
	echo out > /sys/class/gpio/gpio24/direction
	echo out > /sys/class/gpio/gpio23/direction
	echo 1 > /sys/class/gpio/gpio24/value
	echo 1 > /sys/class/gpio/gpio23/value
	modprobe ppp_generic
	modprobe option
	echo 0 > /sys/class/gpio/gpio23/value
	echo "OK"
}

stop() {
	printf "Stopping wireless communications: "
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart|reload}"
	exit 1
esac

exit $?
