#!/bin/sh
#
# start/stop update data
#

start() {
	if [ -f /overlay/update/data.tar.bz2 ]; then
		echo Found data archive for update.
		if bzip2 -t /overlay/update/data.tar.bz2; then
			echo -n Update data checked, unpacking...
			bzcat /overlay/update/data.tar.bz2 | \
				sudo -u www-data -g www-data \
					/bin/sh -c 'tar x -o -C /'
			echo "[DONE]"
		else
			echo Update data invalid, skip updating.
		fi
		rm -f /overlay/update/data.tar.bz2 
	else
		echo Skipping update www-data...
	fi
}

stop() {
	echo Stopping update data...
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart|reload}"
	exit 1
esac

exit $?
