#!/bin/sh
#
# start/stop update data
#

start() {
	# Check filesystem
	mount /overlay/update -o remount,ro,noatime
	mount /overlay -o remount,ro,noatime
	fsck.ext2 -yf /dev/mmcblk0p4
	fsck.ext2 -yf /dev/mmcblk0p3
	# Remount filesystem options
	mount /overlay/update -o remount,rw,noatime
	mount /overlay -o remount,rw,noatime,sync,dirsync
	# place data update on separate partition
	mkdir -p /overlay/update/www-data
	chown www-data:www-data /overlay/update/www-data
	ln -sfT /overlay/update/www-data /var/www/html/update
	sync
	# Then check hard reset command file
	if [ -f /var/www/html/clean ]; then
		echo "Found clean file - erase RW partition"
		rm -rf /overlay/rw/*
		sleep 2
		/sbin/reboot
	fi
	# Then check and extract update data
	if [ -f /var/www/html/update/data.tar.bz2 ]; then
		echo Found data archive for update.
		if bzip2 -t /var/www/html/update/data.tar.bz2; then
			echo -n Cleanup data directory...
			rm -rf /var/www/html/data/*
			echo "[DONE]"
			echo -n Update data checked, unpacking...
			bzcat /var/www/html/update/data.tar.bz2 | \
				sudo -u www-data -g www-data \
					/bin/sh -c 'tar x -o -C /var/www/html/data/'
			echo -n Move update to archive...
				mv /var/www/html/update/data.tar.bz2 \
					/var/www/html/data/archive
			echo "[DONE]"
			sync
		else
			echo Update data invalid, skip updating.
		fi
		rm -f /var/www/html/update/data.tar.bz2
	else
		echo Skipping update www-data...
	fi
}

stop() {
	echo Stopping update data...
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart|reload}"
	exit 1
esac

exit $?
